### ISSUE TITLE
Very Ram Hungry

### ISSUE THREAD

**Issue by RinMaru** [FaithLV/WPF_Spectabis#25] opened 2018-05-28 16:15 UTC
Im not sure if this is an issue or is intended but ive seen this program take up about 2gb of ram. seems a bit much for a frontend

Windows 10 x64
i5 6402P 8GB DDR4
AMD RX 480 4GB

**Comment by FaithLV** [comment] 2018-05-29 17:26
Never had a library anywhere near that size, but that still sounds way too much. 

Could you tell me the size of your Resources/Configs folder? It could be that all the images loaded really do take up that size.

**Comment by FaithLV** [comment] 2018-05-29 19:35
Could you archive your Resources/Configs folder and upload it somewhere so I can test? Don't worry, it doesn't include any personal information other than game file path.

**Comment by RinMaru** [comment] 2018-05-29 20:29
ill upload it to Google Drive

**Comment by RinMaru** [comment] 2018-05-29 21:05
https://drive.google.com/open?id=1bo2cCk-S076OPm_oiDVwHIjRaski7PPd

**Comment by FaithLV** [comment] 2018-05-30 11:21
Thanks! 2GB indeed!

Looks like there's a memory leak in unmanaged code sections, I'll try to find the cause of it.

**Comment by FaithLV** [comment] 2018-05-30 23:09
Issue has been fixed in https://github.com/FaithLV/WPF_Spectabis/commit/ee07b4b3ce520567d761eb0da7f1eceb3804cbda

I have one more idea to improve performance and you should expect an updated release in upcoming days.

**Closed by FaithLV** 2018-05-30 23:09 UTC

**Comment by RinMaru** [comment] 2018-05-30 23:58
awesome thanks ^^ I look forward to the update

**Comment by FaithLV** [comment] 2018-06-03 18:14
Here's the update!
https://github.com/FaithLV/WPF_Spectabis/releases/tag/1.0.8

**Comment by RinMaru** [comment] 2018-06-04 00:33
awesome works like a charm
